var express=require('express')
var app=express()
var bodyparser=require('body-parser')
var cors=require('cors')
var {mongoose}=require('./db')
var contact=require('./controllers/contact')
var blooddonation=require('./controllers/blooddonation')
var bloodequest=require('./controllers/bloodrequest')
// var donor=require('./controllers/donor')
var patient=require('./controllers/patient')
// var script=require("./script")
// app.use("/",script)
app.use(bodyparser.urlencoded({extended:true}))
app.use(bodyparser.json())
app.use(cors({origin:'http://localhost:4200'}))
app.listen(3000,console.log("success"))
app.use('/contact',contact)
app.use('/blooddonation',blooddonation)
app.use('/bloodrequest',bloodequest)
// app.use('/donor',donor)
app.use('/patient',patient)